// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT LightBar

lv_obj_t * ui_LightBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_LightBar;
    cui_LightBar = lv_bar_create(comp_parent);
    lv_bar_set_range(cui_LightBar, 30, 300);
    lv_bar_set_value(cui_LightBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_LightBar, 100, LV_ANIM_OFF);
    lv_obj_set_width(cui_LightBar, 250);
    lv_obj_set_height(cui_LightBar, 24);
    lv_obj_set_x(cui_LightBar, 0);
    lv_obj_set_y(cui_LightBar, -20);
    lv_obj_set_align(cui_LightBar, LV_ALIGN_CENTER);

    lv_obj_set_style_shadow_color(cui_LightBar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_LightBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_LightBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_LightBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(cui_LightBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(cui_LightBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LIGHTBAR_NUM);
    children[UI_COMP_LIGHTBAR_LIGHTBAR] = cui_LightBar;
    lv_obj_add_event_cb(cui_LightBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_LightBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_LightBar_create_hook(cui_LightBar);
    return cui_LightBar;
}

