// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_LabelSpeedLeftFront;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_LabelDistanceLeft;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_LabelSpeedLeftBack;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_LabelDistanceFront;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_LabelDistanceBack;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_LabelSpeedRightFront;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_LabelDistanceRight;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_LabelSpeedRightBack;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_ellipse_1_png);    // assets/Ellipse 1.png
LV_IMG_DECLARE(ui_img_rectangle_1_png);    // assets/Rectangle 1.png
LV_IMG_DECLARE(ui_img_rectangle_10_png);    // assets/Rectangle 10.png
LV_IMG_DECLARE(ui_img_rectangle_11_png);    // assets/Rectangle 11.png
LV_IMG_DECLARE(ui_img_rectangle_12_png);    // assets/Rectangle 12.png
LV_IMG_DECLARE(ui_img_rectangle_13_png);    // assets/Rectangle 13.png
LV_IMG_DECLARE(ui_img_rectangle_14_png);    // assets/Rectangle 14.png
LV_IMG_DECLARE(ui_img_rectangle_15_png);    // assets/Rectangle 15.png
LV_IMG_DECLARE(ui_img_rectangle_16_png);    // assets/Rectangle 16.png
LV_IMG_DECLARE(ui_img_rectangle_2_png);    // assets/Rectangle 2.png
LV_IMG_DECLARE(ui_img_rectangle_3_png);    // assets/Rectangle 3.png
LV_IMG_DECLARE(ui_img_rectangle_5_png);    // assets/Rectangle 5.png
LV_IMG_DECLARE(ui_img_rectangle_6_png);    // assets/Rectangle 6.png
LV_IMG_DECLARE(ui_img_rectangle_7_png);    // assets/Rectangle 7.png
LV_IMG_DECLARE(ui_img_rectangle_8_png);    // assets/Rectangle 8.png
LV_IMG_DECLARE(ui_img_rectangle_9_png);    // assets/Rectangle 9.png



LV_FONT_DECLARE(ui_font_changfangxing);
LV_FONT_DECLARE(ui_font_gouzi48);
LV_FONT_DECLARE(ui_font_guanji48);
LV_FONT_DECLARE(ui_font_jiahao48);
LV_FONT_DECLARE(ui_font_rili48);
LV_FONT_DECLARE(ui_font_shezhi48);
LV_FONT_DECLARE(ui_font_shoudian48);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
